service: mc-server

frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-python-requirements


provider:
  name: aws
  runtime: python3.8
  region: ${env:AWS_REGION}
  environment:
    EC2_INSTANCE_ID: ${env:EC2_INSTANCE_ID}
    USERS_ALLOWED: ${env:USERS_ALLOWED}
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'ec2:DescribeInstances'
            - 'ec2:StartInstances'
            - 'ec2:StopInstances'
          Resource: '*'

functions:
  hello:
    handler: handler.handle_bot
    events:
      - http:
          path: /bot/minecraft
          method: post
          cors: true
